export enum AppState {
  SPLASH = 'SPLASH',
  TOKEN_CHECK = 'TOKEN_CHECK',
  COUNTRY_SELECT = 'COUNTRY_SELECT',
  INITIAL_SCREEN = 'INITIAL_SCREEN',
  LOGIN = 'LOGIN',
  SIGNUP = 'SIGNUP',
  CREATE_TEAM = 'CREATE_TEAM',
  WEBVIEW = 'WEBVIEW',
  LOGOUT = 'LOGOUT',
}
